### ISSUE TITLE
g_plugin error when enabling 0.0.4

### ISSUE THREAD

**Issue by posics** [prrvchr/CloudUcpOOo#1]
Trying to connect to my google drive (and hopefully google sheets!

I get this error when I try to enable CloudUcpOOo 0.0.4 in my libreoffice installation

<class 'NameError'>: name 'g_plugin' is not defined, traceback follows
  File "C:\Program Files\LibreOffice\program\pythonloader.py", line 149, in writeRegistryInfo
    mod = self.getModuleFromUrl( locationUrl )
  File "C:\Program Files\LibreOffice\program\pythonloader.py", line 104, in getModuleFromUrl
    exec(codeobject, mod.__dict__)
  File "C:\Users\pele\AppData\Roaming\LibreOffice\4\user\uno_packages\cache\uno_packages\lu25762litga.tmp_\CloudUcpOOo.oxt\ContentProvider.py", line 34, in <module>
    g_ImplementationName = '%s.ContentProvider' % g_plugin

and another one

(com.sun.star.uno.RuntimeException) { { Message = "<class 'NameError'>: name 'g_plugin' is not defined, traceback follows\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 149, in writeRegistryInfo\X000a    mod = self.getModuleFromUrl( locationUrl )\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 104, in getModuleFromUrl\X000a    exec(codeobject, mod.__dict__)\X000a  File \"C:\\Users\\pele\\AppData\\Roaming\\LibreOffice\\4\\user\\uno_packages\\cache\\uno_packages\\lu25762litga.tmp_\\CloudUcpOOo.oxt\\ContentProvider.py\", line 34, in <module>\X000a    g_ImplementationName = '%s.ContentProvider' % g_plugin\X000a\X000a", Context = (com.sun.star.uno.XInterface) @0 } }

Using LibreOffice 6.3.3.2 (x64)
Build ID: a64200df03143b798afd1ec74a12ab50359878ed
CPU threads: 1; OS: Windows 6.1; UI render: default; VCL: win; 
Locale: en-US (en_US); UI-Language: en-US
Calc: threaded

**Comment by prrvchr** [comment]
Hi posics,

I'm sorry, but the documentation is out of date...

To connect to your Google Drive you need to install:
[OAuth2OOo](https://github.com/prrvchr/OAuth2OOo/raw/master/OAuth2OOo.oxt) 
[gDriveOOo](https://github.com/prrvchr/gDriveOOo/raw/master/gDriveOOo.oxt)
that's all...

It's no longer necessary to install CloudUcpOOo, which is now only a shared library between gDriveOOo, oneDriveOOo and DropboxOOo.

Sorry for this inconvenience and thank you for reporting any malfunction, it helps me to improve the extension.
